routes:
  "13c":
    - Talamban
    - Gov. M. Cuenco Ave.
    - Gaisano Grand Mall (Talamban)
    - University of San Carlos (Talamban)
    - Banilad
    - Banilad Town Center
    - Gaisano Country Mall
    - University of Cebu (Banilad)
    - Paradise Village
    - Cebu Country Club
    - Samantabhadra Institute
    - Arch. Reyes Ave.
    - BIR
    - Cebu Business Park
    - Pag-ibig Fund
    - Ayala Center Cebu
    - Mindanao Ave.
    - Samar Loop
    - Luzon Ave.
    - Tune Hotels
    - Arch. Reyes Ave.
    - Hotel Elizabeth
    - Gorordo Ave.
    - Asilo dela Melagrosa
    - Camp Sutero (Cebu City Police office)
    - Gen. Echavez St.
    - Sikatuna St.
    - Parian
    - Colon St.
    - Gaisano Main
    - University of the Visayas
    - Colonnade Supermarket
    - Colon
    - Pelaez St.
    - University of San Carlos (Main)
    - P. del Rosario St.
    - Imus Ave.
    - M.J. Cuenco Ave.
    - Hipodromo
    - Mactan St.
    - Cebu Business Park
    - Leyte Loop
    - Samar Loop
    - Lexmark
    - Mindanao Ave.
    - Ayala Center Cebu
    - Arch. Reyes Ave.
    - BIR
    - Samantabhadra Institute
    - Gov. M. Cuenco Ave.
    - Banilad
    - UC (Banilad)
    - Gaisano Country Mall
    - Banilad Town Center
    - Foodland
    - University of San Carlos (Talamban)
    - Gaisano Grand Mall (Talamban)
    - Talamban

  "04L":
    - Lahug
    - JY Square Mall
    - Gorordo Ave.
    - Corner Sudlon
    - Corner Beverly Hills
    - Corner Dep-ed (EcoTech)
    - Mormons Church (Church of Jesus Christ of Latter-day Saints)
    - Lahug Brgy Hall
    - University of the Philippines (Cebu)
    - Sugbo Cultural Center
    - Harolds Hotel
    - Tonross Apartelle
    - The Golden Peak Hotel
    - N. Escario Hotel
    - Philhealth
    - Kuya J's Restaurant
    - Cebu Parklane Hotel
    - Grand Cenia Hotel
    - Hongkong Plaza Hotel
    - Cebu Business Park
    - Mindanao Ave.
    - Pag-ibig Fund
    - Ayala Center Cebu
    - Cardinal Rosales Ave.
    - Pope John Paul II Ave.
    - PLDT
    - Carmelite Monastery
    - St. Joseph Parish (Mabolo Church)
    - SM City Cebu
    - SM City Cebu
    - Radisson Hotel
    - Sergio Osmena Blvd.
    - Kaohsiung St.
    - Cebu Daily News
    - A. Soriano Ave.
    - Juan Luna Ave. ext.
    - Pope John Paul II Ave.
    - Mabolo Church
    - Andoks Mabolo
    - Carmelite Monastery
    - San Carlos Seminary College
    - TESDA VII
    - Salinas Drive
    - Cebu IT Park
    - Waterfront Hotel
    - Crowne Garden Hotel
    - JY Square Mall
    - Lahug
routes:
  "12L":
    - Punta Princesa Church
    - Tres de Abril
    - Salvador St.
    - Katipunan St.
    - Tres de Abril St.
    - N. Bacalso Ave.
    - V. Rama Ave.
    - B. Rodriguez Ave.
    - Fuente Osmena Circle
    - Robinsons Place Cebu (Fuente)
    - Mango Ave.
    - Gen. Maxilom Ave.
    - Gorordo Ave. Cebu City Police Station
    - Ayala Road
    - Ayala Terminal
    - Harolds Hotel
    - Escario St.
    - Cebu Provincial Capitol
    - M. Velez St.
    - Banawa
    - R. Duterte St.
    - Rustan's Supermarket (Banawa)
    - Salvador Extension
    - Katipunan St.
    - F. Llamas St.
    - Gaisano Capital (Tisa)
    - Brgy Tisa
    - Punta Princesa
    - Punta Princesa Church
